name: undo_redo
description: "A simple, lightweight package for adding undo/redo functionality to your Flutter apps, suitable for both primitives and complex objects"
version: 0.1.2
homepage: https://github.com/Moasfar-Javed/undo_redo
repository: https://github.com/Moasfar-Javed/undo_redo

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos:

topics:
  - undo
  - redo