name: undo_redo

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: dart format . --set-exit-if-changed
      - name: Analyze
        run: flutter analyze
      - name: Cloneable Test
        run: flutter test --plain-name "Cloneable"
      - name: UndoRedoManager Test
        run: flutter test --plain-name "UndoRedoManager"
        
